app/__init__.py
from .views import PPIBP
from flask_app import PPIApp

class PPIInit():
    flask_app = PPIApp().__get_app__()
    flask_app.static_url_path = flask_app.config.get("STATIC_FOLDER")
    flask_app.static_folder = flask_app.config.get("STATIC_FOLDER")
    flask_app.template_folder = flask_app.config.get("TEMPLATES_FOLDER")
    flask_app.secret_key = flask_app.config.get("SECRET_KEY")
    flask_app.instance_path = flask_app.config.get("INSTANCE_PATH")
    flask_app.register_blueprint(PPIBP)
    def __get_flask__(self):
        return self.flask_app
        

app/views.py
from flask import (render_template,
                Blueprint,
                send_from_directory,
                request,
                redirect,
                url_for,
                session,
                current_app,
                )
from .constants import PPIConstants


PPIBP = Blueprint('PPIBP', __name__)

constants = PPIConstants()
routes = constants.routes
ui_text = constants.ui_text
util_fns = constants.utils_fns

@PPIBP.get(routes.Home.url)
def home():
    return render_template(routes.Home.template,
                            constants = constants,
                            routes = routes,
                            ui_text = ui_text,
                            page_title = routes.Home.title)

@PPIBP.get(routes.Browse.url)
def browse():
    return render_template(routes.Browse.template,
                            constants = constants,
                            routes = routes,
                            ui_text = ui_text,
                            page_title = routes.Browse.title)


@PPIBP.get(routes.Search.url)
def search():
    return render_template(routes.Search.template,
                            constants = constants,
                            routes = routes,
                            ui_text = ui_text,
                            page_title = routes.Search.title)

@PPIBP.get(routes.About.url)
def about():
    return render_template(routes.About.template,
                            constants = constants,
                            routes = routes,
                            ui_text = ui_text,
                            page_title = routes.About.title)

@PPIBP.get(routes.Table_view.url)
def table_view(table):
    table_df = constants.db.get_table_df(table)
    return render_template(routes.Table_view.template,
                            table_df = table_df,
                            constants = constants,
                            routes = routes,
                            ui_text = ui_text,
                            page_title = routes.Table_view.title)

@PPIBP.get(routes.Search_Result.url)
def search_result(table_select, column, term):
    result_df = constants.db.search_term_in_table(table=table_select, column_initials=column, term=term)
    if session.get('filter_dict') == True:
        result_df = constants.db.filter_dataframe(result_df, session['filter_dict'])
        session.pop('filter_dict', default=None)
    return render_template(routes.Table_view.template,
                            constants = constants,
                            routes = routes,
                            ui_text = ui_text,
                            table_df = result_df,
                            page_title = routes.Table_view.title)

@PPIBP.route(routes.download.url)
def download_file(filename):
    directory = current_app.root_path + '/downloads'
    return send_from_directory(directory, filename, as_attachment=True)

@PPIBP.get(routes.Search_Term.url)
def searchCol():
    query_type = request.args['query_type']
    query_term = request.args['search']
    results = constants.db.searchCols(query_type, query_term)
    return results

@PPIBP.get(routes.Get_Search_Term.url)
def get_search_term():
    return render_template(routes.Get_Search_Term.template, constants = constants)

@PPIBP.get(routes.GenerateFile.url)
def generate_file():
    result_type = request.args.get('result-type')
    if result_type == 'search':
        table_select = request.args.get('table-select')
        column = request.args.get('column')
        term = request.args.get('term')
        result_df = constants.db.search_term_in_table(table=table_select, column_initials=column, term=term, limit = 'infinity')
        if session.get('filter_dict') == True:
            result_df = constants.db.filter_dataframe(result_df, session['filter_dict'])

    else:
        table_name = request.args.get('table')
        result_df = constants.db.get_table_df(table_name, limit='infinity')

    result_csv = util_fns.make_csv(result_df)
    return result_csv


@PPIBP.get(routes.Form_submit.url)
def handle_form():
    form_dict = {
        'table-select': request.args.get('table-select'),
        'search-col-1-query-type': request.args.get('search-col-1-query-type'),
        'search-col-1-query-term': request.args.get('search-col-1-query-term')
    }
    session['filter_dict'] = util_fns.create_filter_dict(form_dict, request.args)
    return redirect(url_for('PPIBP.search_result', table_select=form_dict['table-select'], column = form_dict['search-col-1-query-type'], term = form_dict['search-col-1-query-term']))

app/templates/layout.html
{% include "modules/head.html" %}
  <body>
    <div class="wrapper">
    {% include "modules/navbar.html" %}
    <section class="content_container py-5 border-bottom">
      <div class="container-fluid px-5">
    {% block content %}
    {% endblock %}
    </div>
    </section>
    {% include "modules/footer.html" %}
    {% include "modules/scripts.html" %}
  </div>
  </body>
</html>

app/templates/main/about.html
{% extends "layout.html" %}
{% block content %}
        <div class="mx-5">
            <h3>{{ routes.About.title }}</h3>
        </div>
        <div class="container mt-5">
            <div class="card p-5">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <h5 class="">{{ ui_text.about_details['name'] }}</h5>
                            <h5 class="">{{ ui_text.about_details['address'] }}</h5>
                            <h5><a href="mailto:{{ ui_text.about_details['email'] }}" class="text-decoration-none">{{ ui_text['about_details'].email }}</a></h5>
                            <h5 class="">{{ ui_text.about_details['university'] }}</h5></h5> 
                        </div>
                        <div class="embed-responsive embed-responsive-16by9 col-md-8">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.860405454418!2d77.33091981514305!3d28.543915294836953!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce44e80a9461b%3A0x302ec8d3d5cb8d1a!2sAmity%20University%20Noida!5e0!3m2!1sen!2sin!4v1664449229001!5m2!1sen!2sin" style="border:0; height: 100%; width:100%;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" class='embed-responsive-item'></iframe>
                         </div>  
                     </div>                        
             </div>
          </div>
        </div>
{% endblock %}

app/templates/main/browse.html
{% extends "layout.html" %}
{% block content %}
{% include 'modules/browse_db.html' %}
{% endblock %}

app/templates/main/home.html
{% extends "layout.html" %}
{% block content %}
{% include "modules/header.html" %}
{% include "modules/features.html" %}
{% endblock %}

app/templates/main/search.html
{% extends "layout.html" %}
{% block content %}
<div class="mx-5 mt-5">
    <h3>{{routes.Search.title}}</h3>
</div>
<div class="container mt-4">
    <form id="search-form" action="{{ routes.Form_submit.url }}">
      <div class="search-terms">
    </div>
    <p><small>Maximum 4 fields.</small></p>
      <div id="add-btn w-100">
        <button class="btn btn-outline-info w-100" id="add-btn-btn" type="button">Add Search Term</button>
      </div>

        <div class="form-group m-3 mt-4">
          <small>You can select only one item at a time. In case you want to search through all tables, click on All</small>
          <select class="form-select" id="table-select" name="table-select" size="10">
            <option value="All Tables" selected>All Tables</option>
              {% for author in constants.db.author_table_dict %}
              {% for table_obj in constants.db.author_table_dict[author] %}
              {% for table_obj_key in table_obj %}
              <option value="{{ table_obj[table_obj_key] }}">{{ author|capitalize }} {{ table_obj_key }}</option>
              {% endfor %}
              {% endfor %}
              {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-outline-primary w-100 mt-4">Submit</button>
      </form>
    </div>
{% endblock %}

app/templates/main/table.html
{% extends "layout.html" %}
{% block content %}
<div class="mx-5">
    <h3>{{routes.Table_view.title}}</h3>
</div>

<div class="container mt-5">
    <div class="m-5">
        <a class="btn btn-outline-primary" id="download" href="#">Download Complete Dataset</a>
    </div>
    <div class="table-responsive">
    {{ table_df.to_html(classes='view_table table table-striped table-bordered') | safe }}
</div>
</div>
{% endblock %}

app/templates/modules/browse_db.html
        <div class="mx-5">
            <h3>{{ routes.Browse.title }}</h3>
        </div>
        {% for author in constants.db.author_table_dict %}
        <div class="container mx-5 mt-5">
            <div class="">
                <h5 class="text-capitalize">{{ author }}</h5>
            </div>
            <ul class="list-group list-group-flush">
                {% for table_obj in constants.db.author_table_dict[author] %}
                {% for table_obj_key in table_obj %}
                <li class="list-group-item"><a href="/view/{{ table_obj[table_obj_key] | safe }}" class="text-decoration-none" style="color:#351c75;">{{ table_obj_key }}</a></li>
                {% endfor %}
                {% endfor %}
              </ul>
        </div>

        {% endfor %}

app/templates/modules/contact.html
        <!-- Contact section-->
        <section class="bg-light py-5">
            <div class="container px-5 my-5 px-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
                    <h2 class="fw-bolder">Get in touch</h2>
                    <p class="lead mb-0">We'd love to hear from you</p>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">

                        <form id="contactForm">
                            <!-- Name input-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="name" type="text" placeholder="Enter your name...">
                                <label for="name">Full name</label>
                                <div class="invalid-feedback">A name is required.</div>
                            </div>
                            <!-- Email address input-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="email" type="email" placeholder="name@example.com">
                                <label for="email">Email address</label>
                                <div class="invalid-feedback">An email is required.</div>
                                <div class="invalid-feedback">Email is not valid.</div>
                            </div>
                            <!-- Phone number input-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="phone" type="tel" placeholder="(123) 456-7890" >
                                <label for="phone">Phone number</label>
                                <div class="invalid-feedback">A phone number is required.</div>
                            </div>
                            <!-- Message input-->
                            <div class="form-floating mb-3">
                                <textarea class="form-control" id="message" type="text" placeholder="Enter your message here..." style="height: 10rem"></textarea>
                                <label for="message">Message</label>
                            </div>

                            <!-- Submit Button-->
                            <button class="btn btn-primary btn-lg w-100" id="submitButton" type="submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>

app/templates/modules/features.html
<!-- Features section-->
<section class="py-5 border-bottom" id="features">
    <div class="container px-5 my-5">
        <div class="row">
            <div class="col-sm-8">
       <p class="m-5"> {{ ui_text.landing_message }} </p>
    </div>
    <div class="col-sm-4">
       <img src="{{ url_for('static',filename = 'img/ppi_features.png') }}" alt="" class="img-thumbnail">
        </div>
    </div>
    </div>
</section>
<!-- Features section-->
<section class="py-5 border-bottom" id="features_extended">
    <div class="container px-5 my-5">
        <div class="row">
            <div class="col-sm-6">
               <img src="{{ url_for('static',filename = 'img/hive.png') }}" alt="" class="img-thumbnail">
    </div>
    <div class="col-sm-6">
       <img src="{{ url_for('static',filename = 'img/hippie.png') }}" alt="" class="img-thumbnail">
        </div>
    </div>
    </div>
</section>

app/templates/modules/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-5"><p class="m-0 text-center text-white">{{ ui_text.copyright }} &copy; {{ ui_text.software_title }} <span id="date"></span></p></div>
</footer>

app/templates/modules/head.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> {{ page_title }} </title>
        {{ constants.tags_html  | safe }}
    </head>

app/templates/modules/header.html
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="header_inside_wrapper h-100 w-100" style="background-image: url('/static/img/ppi_landing.png');">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            <h1 class="display-5 fw-bolder text-white mb-2">{{ ui_text.landing_title }}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </header>

app/templates/modules/navbar.html
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="{{ routes.Home.url }}">{{ ui_text.software_title }}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% for nav_route in constants.navbar_routes %}
                        <li class="nav-item"><a class="nav-link" href="{{ routes[nav_route].url }}">{{ nav_route }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </nav>

app/templates/modules/scripts.html
{{ constants.tags_script_html  | safe }}

app/templates/modules/search_term.html
<div class="row m-3 search-query">
    <div class="form-group col-md-7 query-term-div">
      <input class="form-control query-term" placeholder="Enter Keyword">
      <datalist class="query-term-list">
      </datalist>  
      </div>
      <div class="form-group col-md-4 query-type-div">
      <select name="" id="" class="query-type form-select">
        {% for column in constants.db.search_keys %}
        <option value="{{ column }}"> {{ column }} </option>
        {% endfor %}
      </select>
      </div>
        <button class="col-md-1 btn btn-outline-warning d-inline remove-btn">Remove</button>
  </div>

app/templates/others/error.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Page Not Found</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    * {
      line-height: 1.2;
      margin: 0;
    }

    html {
      color: #888;
      display: table;
      font-family: sans-serif;
      height: 100%;
      text-align: center;
      width: 100%;
    }

    body {
      display: table-cell;
      vertical-align: middle;
      margin: 2em auto;
    }

    h1 {
      color: #555;
      font-size: 2em;
      font-weight: 400;
    }

    p {
      margin: 0 auto;
      width: 280px;
    }

    #home {
      text-decoration: none;
      color:#0d6dfdd0;
    }

    #home:hover {
      color: #0d6dfd;
    }

    @media only screen and (max-width: 280px) {

      body,
      p {
        width: 95%;
      }

      h1 {
        font-size: 1.5em;
        margin: 0 0 0.3em;
      }

    }
  </style>
</head>

<body>
  <h1>This page does not exist.</h1>
  <p>Sorry, but the page you were trying to view does not exist.</p>
  <p>Please return to <a href="{{ url_for('PPIBP.home') }}" id="home">home page</a></p>
</body>
<script>
</script>
</html>